# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'profile_form.ui'
##
## Created by: Qt User Interface Compiler version 6.7.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QDateEdit,
    QFrame, QGraphicsView, QLabel, QLineEdit,
    QPlainTextEdit, QPushButton, QRadioButton, QSizePolicy,
    QSpinBox, QStackedWidget, QWidget)

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(1000, 600)
        Form.setFocusPolicy(Qt.ClickFocus)
        self.idLabel = QLabel(Form)
        self.idLabel.setObjectName(u"idLabel")
        self.idLabel.setGeometry(QRect(20, 20, 51, 31))
        self.idLabel.setStyleSheet(u"QLabel {\n"
"	font-size: 20px;\n"
"}")
        self.idLabel.setTextFormat(Qt.PlainText)
        self.nameLabel = QLabel(Form)
        self.nameLabel.setObjectName(u"nameLabel")
        self.nameLabel.setGeometry(QRect(80, 20, 491, 31))
        self.nameLabel.setStyleSheet(u"QLabel {\n"
"	font-size: 20px;\n"
"}")
        self.savePushButton = QPushButton(Form)
        self.savePushButton.setObjectName(u"savePushButton")
        self.savePushButton.setGeometry(QRect(840, 20, 141, 31))
        self.discardPushButton = QPushButton(Form)
        self.discardPushButton.setObjectName(u"discardPushButton")
        self.discardPushButton.setGeometry(QRect(680, 20, 151, 31))
        self.stackedWidget = QStackedWidget(Form)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setEnabled(True)
        self.stackedWidget.setGeometry(QRect(20, 60, 961, 481))
        self.stackedWidget.setCursor(QCursor(Qt.CursorShape.ArrowCursor))
        self.stackedWidget.setFocusPolicy(Qt.WheelFocus)
        self.stackedWidget.setFrameShape(QFrame.Box)
        self.stackedWidget.setFrameShadow(QFrame.Sunken)
        self.page_1 = QWidget()
        self.page_1.setObjectName(u"page_1")
        self.photoFrame = QFrame(self.page_1)
        self.photoFrame.setObjectName(u"photoFrame")
        self.photoFrame.setGeometry(QRect(10, 10, 241, 161))
        self.photoFrame.setFrameShape(QFrame.StyledPanel)
        self.photoFrame.setFrameShadow(QFrame.Sunken)
        self.graphicsView = QGraphicsView(self.photoFrame)
        self.graphicsView.setObjectName(u"graphicsView")
        self.graphicsView.setGeometry(QRect(10, 10, 131, 111))
        self.photoPathLabel = QLabel(self.photoFrame)
        self.photoPathLabel.setObjectName(u"photoPathLabel")
        self.photoPathLabel.setGeometry(QRect(10, 130, 221, 16))
        self.photoPathLabel.setStyleSheet(u"QLabel {\n"
"    color: palette(highlight);\n"
"}")
        self.photoPathLabel.setFrameShape(QFrame.NoFrame)
        self.photoPathLabel.setFrameShadow(QFrame.Sunken)
        self.photoPathLabel.setOpenExternalLinks(True)
        self.importPhotoPushButton = QPushButton(self.photoFrame)
        self.importPhotoPushButton.setObjectName(u"importPhotoPushButton")
        self.importPhotoPushButton.setGeometry(QRect(150, 10, 81, 24))
        self.deletePhotoPushButton = QPushButton(self.photoFrame)
        self.deletePhotoPushButton.setObjectName(u"deletePhotoPushButton")
        self.deletePhotoPushButton.setGeometry(QRect(150, 40, 81, 24))
        self.authorizationsFrame = QFrame(self.page_1)
        self.authorizationsFrame.setObjectName(u"authorizationsFrame")
        self.authorizationsFrame.setGeometry(QRect(260, 10, 321, 161))
        self.authorizationsFrame.setFrameShape(QFrame.StyledPanel)
        self.authorizationsFrame.setFrameShadow(QFrame.Sunken)
        self.label_4 = QLabel(self.authorizationsFrame)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 10, 201, 71))
        self.label_4.setWordWrap(True)
        self.label_5 = QLabel(self.authorizationsFrame)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 90, 201, 61))
        self.label_5.setWordWrap(True)
        self.contactFrame = QFrame(self.authorizationsFrame)
        self.contactFrame.setObjectName(u"contactFrame")
        self.contactFrame.setGeometry(QRect(210, 30, 91, 31))
        self.contactFrame.setFrameShape(QFrame.NoFrame)
        self.contactFrame.setFrameShadow(QFrame.Raised)
        self.contactYesRadioButton = QRadioButton(self.contactFrame)
        self.contactYesRadioButton.setObjectName(u"contactYesRadioButton")
        self.contactYesRadioButton.setGeometry(QRect(10, 0, 41, 22))
        self.contactNoRadioButton = QRadioButton(self.contactFrame)
        self.contactNoRadioButton.setObjectName(u"contactNoRadioButton")
        self.contactNoRadioButton.setGeometry(QRect(50, 0, 41, 22))
        self.participationFrame = QFrame(self.authorizationsFrame)
        self.participationFrame.setObjectName(u"participationFrame")
        self.participationFrame.setGeometry(QRect(220, 100, 91, 41))
        self.participationFrame.setFrameShape(QFrame.NoFrame)
        self.participationFrame.setFrameShadow(QFrame.Raised)
        self.participateYesRadioButton = QRadioButton(self.participationFrame)
        self.participateYesRadioButton.setObjectName(u"participateYesRadioButton")
        self.participateYesRadioButton.setGeometry(QRect(0, 10, 41, 22))
        self.participateNoRadioButton = QRadioButton(self.participationFrame)
        self.participateNoRadioButton.setObjectName(u"participateNoRadioButton")
        self.participateNoRadioButton.setGeometry(QRect(40, 10, 41, 22))
        self.cvFrame = QFrame(self.page_1)
        self.cvFrame.setObjectName(u"cvFrame")
        self.cvFrame.setGeometry(QRect(10, 180, 241, 91))
        self.cvFrame.setFrameShape(QFrame.StyledPanel)
        self.cvFrame.setFrameShadow(QFrame.Sunken)
        self.importCVPushButton = QPushButton(self.cvFrame)
        self.importCVPushButton.setObjectName(u"importCVPushButton")
        self.importCVPushButton.setGeometry(QRect(10, 30, 111, 24))
        self.deleteCVPushButton = QPushButton(self.cvFrame)
        self.deleteCVPushButton.setObjectName(u"deleteCVPushButton")
        self.deleteCVPushButton.setGeometry(QRect(130, 30, 101, 24))
        self.label_6 = QLabel(self.cvFrame)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 10, 91, 16))
        self.cvPathLabel = QLabel(self.cvFrame)
        self.cvPathLabel.setObjectName(u"cvPathLabel")
        self.cvPathLabel.setGeometry(QRect(10, 60, 221, 16))
        self.cvPathLabel.setStyleSheet(u"QLabel {\n"
"    color: palette(highlight);\n"
"}")
        self.cvPathLabel.setFrameShape(QFrame.NoFrame)
        self.cvPathLabel.setFrameShadow(QFrame.Sunken)
        self.formsFrame = QFrame(self.page_1)
        self.formsFrame.setObjectName(u"formsFrame")
        self.formsFrame.setGeometry(QRect(260, 180, 321, 91))
        self.formsFrame.setFrameShape(QFrame.StyledPanel)
        self.formsFrame.setFrameShadow(QFrame.Sunken)
        self.label_8 = QLabel(self.formsFrame)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(10, 10, 151, 16))
        self.formsEmailLabel = QLabel(self.formsFrame)
        self.formsEmailLabel.setObjectName(u"formsEmailLabel")
        self.formsEmailLabel.setGeometry(QRect(70, 50, 241, 20))
        self.formsEmailLabel.setFrameShape(QFrame.NoFrame)
        self.formsEmailLabel.setFrameShadow(QFrame.Sunken)
        self.label_10 = QLabel(self.formsFrame)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(10, 50, 51, 16))
        self.label_10.setFrameShape(QFrame.NoFrame)
        self.motivationsFrame = QFrame(self.page_1)
        self.motivationsFrame.setObjectName(u"motivationsFrame")
        self.motivationsFrame.setGeometry(QRect(590, 10, 351, 261))
        self.motivationsFrame.setFrameShape(QFrame.StyledPanel)
        self.motivationsFrame.setFrameShadow(QFrame.Sunken)
        self.label_11 = QLabel(self.motivationsFrame)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(10, 10, 261, 16))
        self.label_11.setFrameShape(QFrame.NoFrame)
        self.checkBox_1 = QCheckBox(self.motivationsFrame)
        self.checkBox_1.setObjectName(u"checkBox_1")
        self.checkBox_1.setGeometry(QRect(10, 30, 301, 22))
        self.checkBox_2 = QCheckBox(self.motivationsFrame)
        self.checkBox_2.setObjectName(u"checkBox_2")
        self.checkBox_2.setGeometry(QRect(10, 50, 321, 22))
        self.checkBox_3 = QCheckBox(self.motivationsFrame)
        self.checkBox_3.setObjectName(u"checkBox_3")
        self.checkBox_3.setGeometry(QRect(10, 70, 331, 22))
        self.checkBox_4 = QCheckBox(self.motivationsFrame)
        self.checkBox_4.setObjectName(u"checkBox_4")
        self.checkBox_4.setGeometry(QRect(10, 90, 331, 22))
        self.checkBox_5 = QCheckBox(self.motivationsFrame)
        self.checkBox_5.setObjectName(u"checkBox_5")
        self.checkBox_5.setGeometry(QRect(10, 110, 321, 22))
        self.checkBox_6 = QCheckBox(self.motivationsFrame)
        self.checkBox_6.setObjectName(u"checkBox_6")
        self.checkBox_6.setGeometry(QRect(10, 130, 331, 22))
        self.checkBox_7 = QCheckBox(self.motivationsFrame)
        self.checkBox_7.setObjectName(u"checkBox_7")
        self.checkBox_7.setGeometry(QRect(10, 150, 331, 22))
        self.checkBox_8 = QCheckBox(self.motivationsFrame)
        self.checkBox_8.setObjectName(u"checkBox_8")
        self.checkBox_8.setGeometry(QRect(10, 170, 331, 22))
        self.checkBox_9 = QCheckBox(self.motivationsFrame)
        self.checkBox_9.setObjectName(u"checkBox_9")
        self.checkBox_9.setGeometry(QRect(10, 190, 331, 22))
        self.checkBox_10 = QCheckBox(self.motivationsFrame)
        self.checkBox_10.setObjectName(u"checkBox_10")
        self.checkBox_10.setGeometry(QRect(10, 210, 331, 22))
        self.label_12 = QLabel(self.page_1)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(20, 290, 121, 16))
        self.completeNameLineEdit = QLineEdit(self.page_1)
        self.completeNameLineEdit.setObjectName(u"completeNameLineEdit")
        self.completeNameLineEdit.setGeometry(QRect(140, 290, 231, 24))
        self.birthFrame = QFrame(self.page_1)
        self.birthFrame.setObjectName(u"birthFrame")
        self.birthFrame.setGeometry(QRect(10, 330, 331, 131))
        self.birthFrame.setFrameShape(QFrame.StyledPanel)
        self.birthFrame.setFrameShadow(QFrame.Sunken)
        self.label_17 = QLabel(self.birthFrame)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(10, 60, 81, 16))
        self.birthDeptComboBox = QComboBox(self.birthFrame)
        self.birthDeptComboBox.setObjectName(u"birthDeptComboBox")
        self.birthDeptComboBox.setGeometry(QRect(100, 60, 221, 24))
        self.birthCityComoBox = QComboBox(self.birthFrame)
        self.birthCityComoBox.setObjectName(u"birthCityComoBox")
        self.birthCityComoBox.setGeometry(QRect(100, 90, 221, 24))
        self.dateEdit = QDateEdit(self.birthFrame)
        self.dateEdit.setObjectName(u"dateEdit")
        self.dateEdit.setGeometry(QRect(100, 20, 111, 25))
        self.dateEdit.setCalendarPopup(True)
        self.label_14 = QLabel(self.birthFrame)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(10, 20, 71, 31))
        self.label_14.setWordWrap(True)
        self.ageLabel = QLabel(self.birthFrame)
        self.ageLabel.setObjectName(u"ageLabel")
        self.ageLabel.setGeometry(QRect(250, 20, 61, 21))
        self.ageLabel.setFrameShape(QFrame.NoFrame)
        self.ageLabel.setFrameShadow(QFrame.Sunken)
        self.ageLabel.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_26 = QLabel(self.birthFrame)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(10, 90, 61, 16))
        self.label = QLabel(self.birthFrame)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(230, 20, 49, 21))
        self.label_13 = QLabel(self.page_1)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(390, 290, 101, 16))
        self.emailLineEdit = QLineEdit(self.page_1)
        self.emailLineEdit.setObjectName(u"emailLineEdit")
        self.emailLineEdit.setGeometry(QRect(500, 290, 201, 24))
        self.idDocFrame = QFrame(self.page_1)
        self.idDocFrame.setObjectName(u"idDocFrame")
        self.idDocFrame.setGeometry(QRect(350, 330, 261, 131))
        self.idDocFrame.setFrameShape(QFrame.StyledPanel)
        self.idDocFrame.setFrameShadow(QFrame.Sunken)
        self.label_15 = QLabel(self.idDocFrame)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(10, 10, 141, 16))
        self.label_19 = QLabel(self.idDocFrame)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(10, 30, 31, 16))
        self.idTypeComboBox = QComboBox(self.idDocFrame)
        self.idTypeComboBox.setObjectName(u"idTypeComboBox")
        self.idTypeComboBox.setGeometry(QRect(50, 30, 201, 24))
        self.label_20 = QLabel(self.idDocFrame)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(10, 60, 49, 16))
        self.label_21 = QLabel(self.idDocFrame)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(10, 80, 81, 31))
        self.label_21.setWordWrap(True)
        self.idNumComboBox = QLineEdit(self.idDocFrame)
        self.idNumComboBox.setObjectName(u"idNumComboBox")
        self.idNumComboBox.setGeometry(QRect(80, 60, 171, 24))
        self.idNumConfirmComboBox = QLineEdit(self.idDocFrame)
        self.idNumConfirmComboBox.setObjectName(u"idNumConfirmComboBox")
        self.idNumConfirmComboBox.setGeometry(QRect(80, 90, 171, 24))
        self.label_22 = QLabel(self.page_1)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(720, 290, 49, 16))
        self.label_23 = QLabel(self.page_1)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(630, 330, 71, 16))
        self.cellphoneLineEdit = QLineEdit(self.page_1)
        self.cellphoneLineEdit.setObjectName(u"cellphoneLineEdit")
        self.cellphoneLineEdit.setGeometry(QRect(770, 290, 171, 24))
        self.otherCellphoneLineEdit = QLineEdit(self.page_1)
        self.otherCellphoneLineEdit.setObjectName(u"otherCellphoneLineEdit")
        self.otherCellphoneLineEdit.setGeometry(QRect(710, 330, 231, 24))
        self.residenceFrame = QFrame(self.page_1)
        self.residenceFrame.setObjectName(u"residenceFrame")
        self.residenceFrame.setGeometry(QRect(620, 360, 321, 101))
        self.residenceFrame.setFrameShape(QFrame.StyledPanel)
        self.residenceFrame.setFrameShadow(QFrame.Sunken)
        self.label_24 = QLabel(self.residenceFrame)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(10, 10, 141, 16))
        self.label_25 = QLabel(self.residenceFrame)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(10, 40, 81, 16))
        self.label_18 = QLabel(self.residenceFrame)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(10, 70, 61, 16))
        self.residenceDeptComboBox = QComboBox(self.residenceFrame)
        self.residenceDeptComboBox.setObjectName(u"residenceDeptComboBox")
        self.residenceDeptComboBox.setGeometry(QRect(90, 40, 221, 24))
        self.residenceCityComboBox = QComboBox(self.residenceFrame)
        self.residenceCityComboBox.setObjectName(u"residenceCityComboBox")
        self.residenceCityComboBox.setGeometry(QRect(90, 70, 221, 24))
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.genreFrame = QFrame(self.page_2)
        self.genreFrame.setObjectName(u"genreFrame")
        self.genreFrame.setGeometry(QRect(10, 10, 181, 141))
        self.genreFrame.setFrameShape(QFrame.StyledPanel)
        self.genreFrame.setFrameShadow(QFrame.Sunken)
        self.label_27 = QLabel(self.genreFrame)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(10, 10, 49, 16))
        self.womanRadioButton = QRadioButton(self.genreFrame)
        self.womanRadioButton.setObjectName(u"womanRadioButton")
        self.womanRadioButton.setGeometry(QRect(10, 30, 91, 22))
        self.manRadioButton = QRadioButton(self.genreFrame)
        self.manRadioButton.setObjectName(u"manRadioButton")
        self.manRadioButton.setGeometry(QRect(10, 50, 91, 22))
        self.nonRadioButton = QRadioButton(self.genreFrame)
        self.nonRadioButton.setObjectName(u"nonRadioButton")
        self.nonRadioButton.setGeometry(QRect(10, 70, 91, 22))
        self.wontSayRadioButton = QRadioButton(self.genreFrame)
        self.wontSayRadioButton.setObjectName(u"wontSayRadioButton")
        self.wontSayRadioButton.setGeometry(QRect(10, 90, 131, 22))
        self.otherGenreRadioButton = QRadioButton(self.genreFrame)
        self.otherGenreRadioButton.setObjectName(u"otherGenreRadioButton")
        self.otherGenreRadioButton.setGeometry(QRect(10, 110, 131, 22))
        self.ethnicityFrame = QFrame(self.page_2)
        self.ethnicityFrame.setObjectName(u"ethnicityFrame")
        self.ethnicityFrame.setGeometry(QRect(200, 10, 251, 101))
        self.ethnicityFrame.setFrameShape(QFrame.StyledPanel)
        self.ethnicityFrame.setFrameShadow(QFrame.Raised)
        self.label_28 = QLabel(self.ethnicityFrame)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(10, 10, 131, 16))
        self.radioButton_10 = QRadioButton(self.ethnicityFrame)
        self.radioButton_10.setObjectName(u"radioButton_10")
        self.radioButton_10.setGeometry(QRect(10, 30, 131, 22))
        self.radioButton_11 = QRadioButton(self.ethnicityFrame)
        self.radioButton_11.setObjectName(u"radioButton_11")
        self.radioButton_11.setGeometry(QRect(10, 50, 131, 22))
        self.radioButton_12 = QRadioButton(self.ethnicityFrame)
        self.radioButton_12.setObjectName(u"radioButton_12")
        self.radioButton_12.setGeometry(QRect(10, 70, 131, 22))
        self.radioButton_13 = QRadioButton(self.ethnicityFrame)
        self.radioButton_13.setObjectName(u"radioButton_13")
        self.radioButton_13.setGeometry(QRect(140, 30, 131, 22))
        self.radioButton_14 = QRadioButton(self.ethnicityFrame)
        self.radioButton_14.setObjectName(u"radioButton_14")
        self.radioButton_14.setGeometry(QRect(140, 50, 131, 22))
        self.radioButton_15 = QRadioButton(self.ethnicityFrame)
        self.radioButton_15.setObjectName(u"radioButton_15")
        self.radioButton_15.setGeometry(QRect(140, 70, 131, 22))
        self.label_29 = QLabel(self.page_2)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(200, 120, 81, 16))
        self.discapacityComboBox = QComboBox(self.page_2)
        self.discapacityComboBox.setObjectName(u"discapacityComboBox")
        self.discapacityComboBox.setGeometry(QRect(280, 120, 171, 24))
        self.educationFrame = QFrame(self.page_2)
        self.educationFrame.setObjectName(u"educationFrame")
        self.educationFrame.setGeometry(QRect(460, 10, 481, 141))
        self.educationFrame.setFrameShape(QFrame.StyledPanel)
        self.educationFrame.setFrameShadow(QFrame.Raised)
        self.label_31 = QLabel(self.educationFrame)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(10, 10, 171, 21))
        self.label_31.setWordWrap(True)
        self.label_32 = QLabel(self.educationFrame)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(10, 40, 111, 21))
        self.label_32.setWordWrap(True)
        self.gradeTitleLineEdit = QLineEdit(self.educationFrame)
        self.gradeTitleLineEdit.setObjectName(u"gradeTitleLineEdit")
        self.gradeTitleLineEdit.setGeometry(QRect(180, 10, 291, 24))
        self.institutionLineEdit = QLineEdit(self.educationFrame)
        self.institutionLineEdit.setObjectName(u"institutionLineEdit")
        self.institutionLineEdit.setGeometry(QRect(180, 40, 291, 24))
        self.label_30 = QLabel(self.educationFrame)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(10, 80, 71, 16))
        self.englishComboBox = QComboBox(self.educationFrame)
        self.englishComboBox.setObjectName(u"englishComboBox")
        self.englishComboBox.setGeometry(QRect(90, 80, 131, 24))
        self.label_33 = QLabel(self.educationFrame)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(10, 110, 71, 16))
        self.frenchComboBox = QComboBox(self.educationFrame)
        self.frenchComboBox.setObjectName(u"frenchComboBox")
        self.frenchComboBox.setGeometry(QRect(90, 110, 131, 24))
        self.label_34 = QLabel(self.educationFrame)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(230, 80, 101, 16))
        self.label_35 = QLabel(self.educationFrame)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(230, 110, 111, 16))
        self.portugueseComboBox = QComboBox(self.educationFrame)
        self.portugueseComboBox.setObjectName(u"portugueseComboBox")
        self.portugueseComboBox.setGeometry(QRect(340, 80, 131, 24))
        self.otherIdiomComboBox = QComboBox(self.educationFrame)
        self.otherIdiomComboBox.setObjectName(u"otherIdiomComboBox")
        self.otherIdiomComboBox.setGeometry(QRect(340, 110, 131, 24))
        self.postdegreeFrame = QFrame(self.page_2)
        self.postdegreeFrame.setObjectName(u"postdegreeFrame")
        self.postdegreeFrame.setGeometry(QRect(10, 170, 931, 141))
        self.postdegreeFrame.setFrameShape(QFrame.StyledPanel)
        self.postdegreeFrame.setFrameShadow(QFrame.Raised)
        self.label_36 = QLabel(self.postdegreeFrame)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(10, 10, 181, 16))
        self.pdYesRadioButton = QRadioButton(self.postdegreeFrame)
        self.pdYesRadioButton.setObjectName(u"pdYesRadioButton")
        self.pdYesRadioButton.setGeometry(QRect(190, 10, 41, 22))
        self.pdNoRadioButton = QRadioButton(self.postdegreeFrame)
        self.pdNoRadioButton.setObjectName(u"pdNoRadioButton")
        self.pdNoRadioButton.setGeometry(QRect(240, 10, 41, 22))
        self.postdregree1Frame = QFrame(self.postdegreeFrame)
        self.postdregree1Frame.setObjectName(u"postdregree1Frame")
        self.postdregree1Frame.setGeometry(QRect(20, 40, 291, 91))
        self.postdregree1Frame.setFrameShape(QFrame.StyledPanel)
        self.postdregree1Frame.setFrameShadow(QFrame.Raised)
        self.pd1LevelComboBox = QComboBox(self.postdregree1Frame)
        self.pd1LevelComboBox.setObjectName(u"pd1LevelComboBox")
        self.pd1LevelComboBox.setGeometry(QRect(10, 30, 171, 24))
        self.pd1StateComboBox = QComboBox(self.postdregree1Frame)
        self.pd1StateComboBox.setObjectName(u"pd1StateComboBox")
        self.pd1StateComboBox.setGeometry(QRect(190, 30, 91, 24))
        self.pd1NameLineEdit = QLineEdit(self.postdregree1Frame)
        self.pd1NameLineEdit.setObjectName(u"pd1NameLineEdit")
        self.pd1NameLineEdit.setGeometry(QRect(10, 60, 271, 24))
        self.label_37 = QLabel(self.postdregree1Frame)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(10, 10, 91, 16))
        self.postdegree2Frame = QFrame(self.postdegreeFrame)
        self.postdegree2Frame.setObjectName(u"postdegree2Frame")
        self.postdegree2Frame.setGeometry(QRect(320, 40, 291, 91))
        self.postdegree2Frame.setFrameShape(QFrame.StyledPanel)
        self.postdegree2Frame.setFrameShadow(QFrame.Raised)
        self.pd2LevelComboBox = QComboBox(self.postdegree2Frame)
        self.pd2LevelComboBox.setObjectName(u"pd2LevelComboBox")
        self.pd2LevelComboBox.setGeometry(QRect(10, 30, 171, 24))
        self.pd2StateComboBox = QComboBox(self.postdegree2Frame)
        self.pd2StateComboBox.setObjectName(u"pd2StateComboBox")
        self.pd2StateComboBox.setGeometry(QRect(190, 30, 91, 24))
        self.pd2NameLineEdit = QLineEdit(self.postdegree2Frame)
        self.pd2NameLineEdit.setObjectName(u"pd2NameLineEdit")
        self.pd2NameLineEdit.setGeometry(QRect(10, 60, 271, 24))
        self.label_40 = QLabel(self.postdegree2Frame)
        self.label_40.setObjectName(u"label_40")
        self.label_40.setGeometry(QRect(10, 10, 121, 16))
        self.postdegree3Frame = QFrame(self.postdegreeFrame)
        self.postdegree3Frame.setObjectName(u"postdegree3Frame")
        self.postdegree3Frame.setGeometry(QRect(620, 40, 291, 91))
        self.postdegree3Frame.setFrameShape(QFrame.StyledPanel)
        self.postdegree3Frame.setFrameShadow(QFrame.Raised)
        self.pd3LevelComboBox = QComboBox(self.postdegree3Frame)
        self.pd3LevelComboBox.setObjectName(u"pd3LevelComboBox")
        self.pd3LevelComboBox.setGeometry(QRect(10, 30, 171, 24))
        self.pd3StateComboBox = QComboBox(self.postdegree3Frame)
        self.pd3StateComboBox.setObjectName(u"pd3StateComboBox")
        self.pd3StateComboBox.setGeometry(QRect(190, 30, 91, 24))
        self.pd3NameLineEdit = QLineEdit(self.postdegree3Frame)
        self.pd3NameLineEdit.setObjectName(u"pd3NameLineEdit")
        self.pd3NameLineEdit.setGeometry(QRect(10, 60, 271, 24))
        self.label_41 = QLabel(self.postdegree3Frame)
        self.label_41.setObjectName(u"label_41")
        self.label_41.setGeometry(QRect(10, 10, 161, 16))
        self.mvFrame = QFrame(self.page_2)
        self.mvFrame.setObjectName(u"mvFrame")
        self.mvFrame.setGeometry(QRect(10, 320, 931, 121))
        self.mvFrame.setFrameShape(QFrame.StyledPanel)
        self.mvFrame.setFrameShadow(QFrame.Raised)
        self.label_42 = QLabel(self.mvFrame)
        self.label_42.setObjectName(u"label_42")
        self.label_42.setGeometry(QRect(10, 10, 301, 16))
        self.mvYesRadioButton = QRadioButton(self.mvFrame)
        self.mvYesRadioButton.setObjectName(u"mvYesRadioButton")
        self.mvYesRadioButton.setGeometry(QRect(320, 10, 41, 22))
        self.mvNoRadioButton = QRadioButton(self.mvFrame)
        self.mvNoRadioButton.setObjectName(u"mvNoRadioButton")
        self.mvNoRadioButton.setGeometry(QRect(370, 10, 41, 22))
        self.mv1Frame = QFrame(self.mvFrame)
        self.mv1Frame.setObjectName(u"mv1Frame")
        self.mv1Frame.setGeometry(QRect(20, 40, 291, 71))
        self.mv1Frame.setFrameShape(QFrame.StyledPanel)
        self.mv1Frame.setFrameShadow(QFrame.Raised)
        self.mv1NameComboBox = QComboBox(self.mv1Frame)
        self.mv1NameComboBox.setObjectName(u"mv1NameComboBox")
        self.mv1NameComboBox.setGeometry(QRect(10, 40, 271, 24))
        self.label_45 = QLabel(self.mv1Frame)
        self.label_45.setObjectName(u"label_45")
        self.label_45.setGeometry(QRect(10, 10, 91, 16))
        self.label_46 = QLabel(self.mv1Frame)
        self.label_46.setObjectName(u"label_46")
        self.label_46.setGeometry(QRect(170, 10, 31, 16))
        self.mv1YearSpinBox = QSpinBox(self.mv1Frame)
        self.mv1YearSpinBox.setObjectName(u"mv1YearSpinBox")
        self.mv1YearSpinBox.setGeometry(QRect(210, 10, 71, 25))
        self.mv2Frame = QFrame(self.mvFrame)
        self.mv2Frame.setObjectName(u"mv2Frame")
        self.mv2Frame.setGeometry(QRect(320, 40, 291, 71))
        self.mv2Frame.setFrameShape(QFrame.StyledPanel)
        self.mv2Frame.setFrameShadow(QFrame.Raised)
        self.mv2NameComboBox = QComboBox(self.mv2Frame)
        self.mv2NameComboBox.setObjectName(u"mv2NameComboBox")
        self.mv2NameComboBox.setGeometry(QRect(10, 40, 271, 24))
        self.label_47 = QLabel(self.mv2Frame)
        self.label_47.setObjectName(u"label_47")
        self.label_47.setGeometry(QRect(10, 10, 141, 16))
        self.label_48 = QLabel(self.mv2Frame)
        self.label_48.setObjectName(u"label_48")
        self.label_48.setGeometry(QRect(170, 10, 31, 16))
        self.mv2YearSpinBox = QSpinBox(self.mv2Frame)
        self.mv2YearSpinBox.setObjectName(u"mv2YearSpinBox")
        self.mv2YearSpinBox.setGeometry(QRect(210, 10, 71, 25))
        self.mv3Frame = QFrame(self.mvFrame)
        self.mv3Frame.setObjectName(u"mv3Frame")
        self.mv3Frame.setGeometry(QRect(620, 40, 291, 71))
        self.mv3Frame.setFrameShape(QFrame.StyledPanel)
        self.mv3Frame.setFrameShadow(QFrame.Raised)
        self.mv3NameComboBox = QComboBox(self.mv3Frame)
        self.mv3NameComboBox.setObjectName(u"mv3NameComboBox")
        self.mv3NameComboBox.setGeometry(QRect(10, 40, 271, 24))
        self.label_49 = QLabel(self.mv3Frame)
        self.label_49.setObjectName(u"label_49")
        self.label_49.setGeometry(QRect(10, 10, 151, 16))
        self.label_50 = QLabel(self.mv3Frame)
        self.label_50.setObjectName(u"label_50")
        self.label_50.setGeometry(QRect(170, 10, 31, 16))
        self.mv3YearSpinBox = QSpinBox(self.mv3Frame)
        self.mv3YearSpinBox.setObjectName(u"mv3YearSpinBox")
        self.mv3YearSpinBox.setGeometry(QRect(210, 10, 71, 25))
        self.mlkFrame = QFrame(self.page_2)
        self.mlkFrame.setObjectName(u"mlkFrame")
        self.mlkFrame.setGeometry(QRect(10, 450, 461, 21))
        self.mlkFrame.setFrameShape(QFrame.NoFrame)
        self.mlkFrame.setFrameShadow(QFrame.Raised)
        self.mlkNoRadioButton = QRadioButton(self.mlkFrame)
        self.mlkNoRadioButton.setObjectName(u"mlkNoRadioButton")
        self.mlkNoRadioButton.setGeometry(QRect(350, 0, 41, 22))
        self.mlkYesRadioButton = QRadioButton(self.mlkFrame)
        self.mlkYesRadioButton.setObjectName(u"mlkYesRadioButton")
        self.mlkYesRadioButton.setGeometry(QRect(300, 0, 41, 22))
        self.label_51 = QLabel(self.mlkFrame)
        self.label_51.setObjectName(u"label_51")
        self.label_51.setGeometry(QRect(10, 0, 271, 16))
        self.fulbrightFrame = QFrame(self.page_2)
        self.fulbrightFrame.setObjectName(u"fulbrightFrame")
        self.fulbrightFrame.setGeometry(QRect(480, 450, 471, 21))
        self.fulbrightFrame.setFrameShape(QFrame.NoFrame)
        self.fulbrightFrame.setFrameShadow(QFrame.Raised)
        self.fbNoRadioButton = QRadioButton(self.fulbrightFrame)
        self.fbNoRadioButton.setObjectName(u"fbNoRadioButton")
        self.fbNoRadioButton.setGeometry(QRect(420, 0, 41, 22))
        self.fbYesRadioButton = QRadioButton(self.fulbrightFrame)
        self.fbYesRadioButton.setObjectName(u"fbYesRadioButton")
        self.fbYesRadioButton.setGeometry(QRect(380, 0, 41, 22))
        self.label_52 = QLabel(self.fulbrightFrame)
        self.label_52.setObjectName(u"label_52")
        self.label_52.setGeometry(QRect(0, 0, 371, 16))
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QWidget()
        self.page_3.setObjectName(u"page_3")
        self.experienceFrame = QFrame(self.page_3)
        self.experienceFrame.setObjectName(u"experienceFrame")
        self.experienceFrame.setGeometry(QRect(10, 50, 541, 81))
        self.experienceFrame.setFrameShape(QFrame.StyledPanel)
        self.experienceFrame.setFrameShadow(QFrame.Raised)
        self.label_59 = QLabel(self.experienceFrame)
        self.label_59.setObjectName(u"label_59")
        self.label_59.setGeometry(QRect(10, 10, 141, 16))
        self.label_60 = QLabel(self.experienceFrame)
        self.label_60.setObjectName(u"label_60")
        self.label_60.setGeometry(QRect(10, 30, 101, 41))
        self.label_60.setWordWrap(True)
        self.label_61 = QLabel(self.experienceFrame)
        self.label_61.setObjectName(u"label_61")
        self.label_61.setGeometry(QRect(380, 30, 81, 41))
        self.label_61.setWordWrap(True)
        self.expSectorComboBox = QComboBox(self.experienceFrame)
        self.expSectorComboBox.setObjectName(u"expSectorComboBox")
        self.expSectorComboBox.setGeometry(QRect(110, 40, 261, 24))
        self.expYearsComboBox = QComboBox(self.experienceFrame)
        self.expYearsComboBox.setObjectName(u"expYearsComboBox")
        self.expYearsComboBox.setGeometry(QRect(450, 40, 81, 24))
        self.label_63 = QLabel(self.page_3)
        self.label_63.setObjectName(u"label_63")
        self.label_63.setGeometry(QRect(500, 10, 49, 16))
        self.linkedInLineEdit = QLineEdit(self.page_3)
        self.linkedInLineEdit.setObjectName(u"linkedInLineEdit")
        self.linkedInLineEdit.setGeometry(QRect(560, 10, 271, 24))
        self.viewLinkedInPushButton = QPushButton(self.page_3)
        self.viewLinkedInPushButton.setObjectName(u"viewLinkedInPushButton")
        self.viewLinkedInPushButton.setGeometry(QRect(840, 10, 101, 24))
        self.comboBox = QComboBox(self.page_3)
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(80, 10, 391, 24))
        self.comboBox.setEditable(True)
        self.label_53 = QLabel(self.page_3)
        self.label_53.setObjectName(u"label_53")
        self.label_53.setGeometry(QRect(10, 10, 71, 16))
        self.frame = QFrame(self.page_3)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(10, 140, 541, 331))
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.profilePlainTextEdit = QPlainTextEdit(self.frame)
        self.profilePlainTextEdit.setObjectName(u"profilePlainTextEdit")
        self.profilePlainTextEdit.setGeometry(QRect(10, 50, 521, 271))
        self.label_62 = QLabel(self.frame)
        self.label_62.setObjectName(u"label_62")
        self.label_62.setGeometry(QRect(10, 10, 81, 16))
        self.pushButton = QPushButton(self.frame)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(420, 20, 111, 24))
        self.currentJobFrame = QFrame(self.page_3)
        self.currentJobFrame.setObjectName(u"currentJobFrame")
        self.currentJobFrame.setGeometry(QRect(560, 50, 381, 421))
        self.currentJobFrame.setFrameShape(QFrame.StyledPanel)
        self.currentJobFrame.setFrameShadow(QFrame.Raised)
        self.label_54 = QLabel(self.currentJobFrame)
        self.label_54.setObjectName(u"label_54")
        self.label_54.setGeometry(QRect(10, 10, 221, 16))
        self.companyLineEdit = QLineEdit(self.currentJobFrame)
        self.companyLineEdit.setObjectName(u"companyLineEdit")
        self.companyLineEdit.setGeometry(QRect(110, 30, 261, 24))
        self.label_55 = QLabel(self.currentJobFrame)
        self.label_55.setObjectName(u"label_55")
        self.label_55.setGeometry(QRect(10, 30, 101, 16))
        self.sectorComboBox = QComboBox(self.currentJobFrame)
        self.sectorComboBox.setObjectName(u"sectorComboBox")
        self.sectorComboBox.setGeometry(QRect(60, 60, 311, 24))
        self.label_56 = QLabel(self.currentJobFrame)
        self.label_56.setObjectName(u"label_56")
        self.label_56.setGeometry(QRect(10, 60, 49, 16))
        self.label_57 = QLabel(self.currentJobFrame)
        self.label_57.setObjectName(u"label_57")
        self.label_57.setGeometry(QRect(10, 90, 31, 16))
        self.rolComboBox = QComboBox(self.currentJobFrame)
        self.rolComboBox.setObjectName(u"rolComboBox")
        self.rolComboBox.setGeometry(QRect(60, 90, 131, 24))
        self.jobDescriptionPlainTextEdit = QPlainTextEdit(self.currentJobFrame)
        self.jobDescriptionPlainTextEdit.setObjectName(u"jobDescriptionPlainTextEdit")
        self.jobDescriptionPlainTextEdit.setGeometry(QRect(10, 140, 361, 271))
        self.label_58 = QLabel(self.currentJobFrame)
        self.label_58.setObjectName(u"label_58")
        self.label_58.setGeometry(QRect(10, 120, 231, 16))
        self.pushButton_2 = QPushButton(self.currentJobFrame)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(260, 110, 111, 24))
        self.stackedWidget.addWidget(self.page_3)
        self.nextPagePushButton = QPushButton(Form)
        self.nextPagePushButton.setObjectName(u"nextPagePushButton")
        self.nextPagePushButton.setGeometry(QRect(840, 550, 141, 31))
        self.previousPagePushButton = QPushButton(Form)
        self.previousPagePushButton.setObjectName(u"previousPagePushButton")
        self.previousPagePushButton.setGeometry(QRect(20, 550, 141, 31))
        self.navigationLabel = QLabel(Form)
        self.navigationLabel.setObjectName(u"navigationLabel")
        self.navigationLabel.setGeometry(QRect(470, 560, 81, 16))

        self.retranslateUi(Form)

        self.stackedWidget.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.idLabel.setText(QCoreApplication.translate("Form", u"0000", None))
        self.nameLabel.setText(QCoreApplication.translate("Form", u"Fulano Pepito P\u00e9rez de Tal", None))
        self.savePushButton.setText(QCoreApplication.translate("Form", u"Guardar", None))
        self.discardPushButton.setText(QCoreApplication.translate("Form", u"Descartar cambios", None))
        self.photoPathLabel.setText(QCoreApplication.translate("Form", u"enlace", None))
        self.importPhotoPushButton.setText(QCoreApplication.translate("Form", u"Importar", None))
        self.deletePhotoPushButton.setText(QCoreApplication.translate("Form", u"Eliminar", None))
        self.label_4.setText(QCoreApplication.translate("Form", u"\u00bfAutoriza a la Corporaci\u00f3n Manos Visibles que se le contacte de forma telef\u00f3nica, mensaje de texto o via correo electr\u00f3nico?", None))
        self.label_5.setText(QCoreApplication.translate("Form", u"\u00bfLe gustar\u00eda hacer parte del Banco de Hojas de Vida del programa Talento Visible y participar en postulaciones laborales? ", None))
        self.contactYesRadioButton.setText(QCoreApplication.translate("Form", u"S\u00ed", None))
        self.contactNoRadioButton.setText(QCoreApplication.translate("Form", u"No", None))
        self.participateYesRadioButton.setText(QCoreApplication.translate("Form", u"S\u00ed", None))
        self.participateNoRadioButton.setText(QCoreApplication.translate("Form", u"No", None))
        self.importCVPushButton.setText(QCoreApplication.translate("Form", u"Importar", None))
        self.deleteCVPushButton.setText(QCoreApplication.translate("Form", u"Eliminar", None))
        self.label_6.setText(QCoreApplication.translate("Form", u"Hoja de vida", None))
        self.cvPathLabel.setText(QCoreApplication.translate("Form", u"enlace", None))
        self.label_8.setText(QCoreApplication.translate("Form", u"Informaci\u00f3n formulario", None))
        self.formsEmailLabel.setText(QCoreApplication.translate("Form", u"Enlace", None))
        self.label_10.setText(QCoreApplication.translate("Form", u"Correo", None))
        self.label_11.setText(QCoreApplication.translate("Form", u"Motivaciones", None))
        self.checkBox_1.setText(QCoreApplication.translate("Form", u"Buscar nuevas oportunidades laborales", None))
        self.checkBox_2.setText(QCoreApplication.translate("Form", u"Adquirir aptitudes profesionales pra avanzar en la carrera", None))
        self.checkBox_3.setText(QCoreApplication.translate("Form", u"Ampliar su red o gestionar su perfil profesional", None))
        self.checkBox_4.setText(QCoreApplication.translate("Form", u"Tener oportunidades de pr\u00e1cticas en empresas", None))
        self.checkBox_5.setText(QCoreApplication.translate("Form", u"Participar en ferias laborales", None))
        self.checkBox_6.setText(QCoreApplication.translate("Form", u"Recibir informaci\u00f3n de ofertas laborales", None))
        self.checkBox_7.setText(QCoreApplication.translate("Form", u"Acceder a cursos impartidos por expertos", None))
        self.checkBox_8.setText(QCoreApplication.translate("Form", u"Acceder a formaci\u00f3n virtual con contenidos en plataformas", None))
        self.checkBox_9.setText(QCoreApplication.translate("Form", u"Conectar con empresas", None))
        self.checkBox_10.setText(QCoreApplication.translate("Form", u"Acceso a becas de estudio", None))
        self.label_12.setText(QCoreApplication.translate("Form", u"Nombres y apellidos", None))
        self.label_17.setText(QCoreApplication.translate("Form", u"Departamento", None))
        self.label_14.setText(QCoreApplication.translate("Form", u"Fecha de nacimiento", None))
        self.ageLabel.setText(QCoreApplication.translate("Form", u"-1 a\u00f1os", None))
        self.label_26.setText(QCoreApplication.translate("Form", u"Municipio", None))
        self.label.setText(QCoreApplication.translate("Form", u"Edad:", None))
        self.label_13.setText(QCoreApplication.translate("Form", u"Correo electr\u00f3nico", None))
        self.label_15.setText(QCoreApplication.translate("Form", u"Documento de identidad", None))
        self.label_19.setText(QCoreApplication.translate("Form", u"Tipo", None))
        self.label_20.setText(QCoreApplication.translate("Form", u"N\u00famero", None))
        self.label_21.setText(QCoreApplication.translate("Form", u"Confirmar n\u00famero", None))
        self.label_22.setText(QCoreApplication.translate("Form", u"Celular", None))
        self.label_23.setText(QCoreApplication.translate("Form", u"Otro celular", None))
        self.label_24.setText(QCoreApplication.translate("Form", u"Lugar de residencia", None))
        self.label_25.setText(QCoreApplication.translate("Form", u"Departamento", None))
        self.label_18.setText(QCoreApplication.translate("Form", u"Municipio", None))
        self.label_27.setText(QCoreApplication.translate("Form", u"G\u00e9nero", None))
        self.womanRadioButton.setText(QCoreApplication.translate("Form", u"Mujer", None))
        self.manRadioButton.setText(QCoreApplication.translate("Form", u"Hombre", None))
        self.nonRadioButton.setText(QCoreApplication.translate("Form", u"No binario", None))
        self.wontSayRadioButton.setText(QCoreApplication.translate("Form", u"Prefiero no decirlo", None))
        self.otherGenreRadioButton.setText(QCoreApplication.translate("Form", u"Otro", None))
        self.label_28.setText(QCoreApplication.translate("Form", u"Grupo \u00e9tnico o cultural", None))
        self.radioButton_10.setText(QCoreApplication.translate("Form", u"Afrodescendientes", None))
        self.radioButton_11.setText(QCoreApplication.translate("Form", u"Blancos", None))
        self.radioButton_12.setText(QCoreApplication.translate("Form", u"Ind\u00edgenas", None))
        self.radioButton_13.setText(QCoreApplication.translate("Form", u"Mestizos", None))
        self.radioButton_14.setText(QCoreApplication.translate("Form", u"Rrom (Gitanos)", None))
        self.radioButton_15.setText(QCoreApplication.translate("Form", u"Ninguno", None))
        self.label_29.setText(QCoreApplication.translate("Form", u"Discapacidad", None))
        self.label_31.setText(QCoreApplication.translate("Form", u"Titulo pregrado o bachillerato", None))
        self.label_32.setText(QCoreApplication.translate("Form", u"Instituci\u00f3n educativa", None))
        self.label_30.setText(QCoreApplication.translate("Form", u"Nivel Ingl\u00e9s", None))
        self.label_33.setText(QCoreApplication.translate("Form", u"Nivel franc\u00e9s", None))
        self.label_34.setText(QCoreApplication.translate("Form", u"Nivel portugu\u00e9s", None))
        self.label_35.setText(QCoreApplication.translate("Form", u"Nivel otros idiomas", None))
        self.label_36.setText(QCoreApplication.translate("Form", u"\u00bfTiene estudios de postgrado?", None))
        self.pdYesRadioButton.setText(QCoreApplication.translate("Form", u"S\u00ed", None))
        self.pdNoRadioButton.setText(QCoreApplication.translate("Form", u"No", None))
        self.pd1LevelComboBox.setPlaceholderText(QCoreApplication.translate("Form", u"Nivel de postgrado", None))
        self.pd1StateComboBox.setCurrentText("")
        self.pd1StateComboBox.setPlaceholderText(QCoreApplication.translate("Form", u"Estado", None))
        self.pd1NameLineEdit.setPlaceholderText(QCoreApplication.translate("Form", u"Nombre de postgrado", None))
        self.label_37.setText(QCoreApplication.translate("Form", u"Postgrado 1", None))
        self.pd2LevelComboBox.setPlaceholderText(QCoreApplication.translate("Form", u"Nivel de postgrado", None))
        self.pd2StateComboBox.setCurrentText("")
        self.pd2StateComboBox.setPlaceholderText(QCoreApplication.translate("Form", u"Estado", None))
        self.pd2NameLineEdit.setPlaceholderText(QCoreApplication.translate("Form", u"Nombre de postgrado", None))
        self.label_40.setText(QCoreApplication.translate("Form", u"Postgrado 2 (opcional)", None))
        self.pd3LevelComboBox.setPlaceholderText(QCoreApplication.translate("Form", u"Nivel de postgrado", None))
        self.pd3StateComboBox.setCurrentText("")
        self.pd3StateComboBox.setPlaceholderText(QCoreApplication.translate("Form", u"Estado", None))
        self.pd3NameLineEdit.setPlaceholderText(QCoreApplication.translate("Form", u"Nombre de postgrado", None))
        self.label_41.setText(QCoreApplication.translate("Form", u"Postgrado 3 (opcional)", None))
        self.label_42.setText(QCoreApplication.translate("Form", u"\u00bfHa participado en alg\u00fan programa de manos visibles?", None))
        self.mvYesRadioButton.setText(QCoreApplication.translate("Form", u"S\u00ed", None))
        self.mvNoRadioButton.setText(QCoreApplication.translate("Form", u"No", None))
        self.mv1NameComboBox.setPlaceholderText(QCoreApplication.translate("Form", u"Nombre programa Manos Visibles", None))
        self.label_45.setText(QCoreApplication.translate("Form", u"Programa 1", None))
        self.label_46.setText(QCoreApplication.translate("Form", u"A\u00f1o", None))
        self.mv2NameComboBox.setPlaceholderText(QCoreApplication.translate("Form", u"Nombre programa Manos Visibles", None))
        self.label_47.setText(QCoreApplication.translate("Form", u"Programa 2 (opcional)", None))
        self.label_48.setText(QCoreApplication.translate("Form", u"A\u00f1o", None))
        self.mv3NameComboBox.setPlaceholderText(QCoreApplication.translate("Form", u"Nombre programa Manos Visibles", None))
        self.label_49.setText(QCoreApplication.translate("Form", u"Programa 3 (opcional)", None))
        self.label_50.setText(QCoreApplication.translate("Form", u"A\u00f1o", None))
        self.mlkNoRadioButton.setText(QCoreApplication.translate("Form", u"No", None))
        self.mlkYesRadioButton.setText(QCoreApplication.translate("Form", u"S\u00ed", None))
        self.label_51.setText(QCoreApplication.translate("Form", u"\u00bfBeneficiario del programa Martin Luther King Jr.?", None))
        self.fbNoRadioButton.setText(QCoreApplication.translate("Form", u"No", None))
        self.fbYesRadioButton.setText(QCoreApplication.translate("Form", u"S\u00ed", None))
        self.label_52.setText(QCoreApplication.translate("Form", u"\u00bfHa participado en Seminario de Liderazgo para becarios Fulbright?", None))
        self.label_59.setText(QCoreApplication.translate("Form", u"Experiencia laboral", None))
        self.label_60.setText(QCoreApplication.translate("Form", u"Sector con mayor experiencia", None))
        self.label_61.setText(QCoreApplication.translate("Form", u"A\u00f1os de experiencia", None))
        self.label_63.setText(QCoreApplication.translate("Form", u"LinkedIn", None))
        self.viewLinkedInPushButton.setText(QCoreApplication.translate("Form", u"Ver LinkedIn", None))
        self.label_53.setText(QCoreApplication.translate("Form", u"Ocupaci\u00f3n", None))
        self.label_62.setText(QCoreApplication.translate("Form", u"Perfil laboral", None))
        self.pushButton.setText(QCoreApplication.translate("Form", u"Mejorar con IA", None))
        self.label_54.setText(QCoreApplication.translate("Form", u"Trabajo actual", None))
        self.label_55.setText(QCoreApplication.translate("Form", u"Nombre empresa", None))
        self.label_56.setText(QCoreApplication.translate("Form", u"Sector", None))
        self.label_57.setText(QCoreApplication.translate("Form", u"Rol", None))
        self.label_58.setText(QCoreApplication.translate("Form", u"Descripci\u00f3n del rol en la empresa o sector", None))
        self.pushButton_2.setText(QCoreApplication.translate("Form", u"Mejorar con IA", None))
        self.nextPagePushButton.setText(QCoreApplication.translate("Form", u"Siguiente", None))
        self.previousPagePushButton.setText(QCoreApplication.translate("Form", u"Anterior", None))
        self.navigationLabel.setText(QCoreApplication.translate("Form", u"P\u00e1gina 1 de 3", None))
    # retranslateUi

